### ISSUE TITLE
 <script> isn’t executed if created by react-basic-hooks

### ISSUE THREAD

**Issue by Hi-Angel** [purescript-react/purescript-react-basic-hooks#76]
From what I found on JS behavior this isn't expected behavior, usually inserting `<script>` does execute it.

I searched over `Props_script` for something like "enableExecution" but found nothing. I don't suppose this is expected to happen.

# Steps to reproduce

1. Create new project with `spago init`
2. Create `index.html` as
    ```xml
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="styles.css">
    </head>
    <body>
      <div id="root"></div>
      <script src="index.js"></script>
    </body>
    </html>
    ```
3. Put this code to `src/Main.purs`
    ```haskell
    module Main where

    import Prelude

    import Data.Maybe (Maybe(..))
    import Effect (Effect)
    import Effect.Exception (throw)
    import React.Basic.DOM as R
    import React.Basic.DOM.Client (createRoot, renderRoot)
    import React.Basic.Hooks (Component, component)
    import Web.DOM.NonElementParentNode (getElementById)
    import Web.HTML (window)
    import Web.HTML.HTMLDocument (toNonElementParentNode)
    import Web.HTML.Window (document)

    main :: Effect Unit
    main = do
      doc <- document =<< window
      root <- getElementById "root" $ toNonElementParentNode doc
      case root of
        Nothing -> throw "Could not find root."
        Just container -> do
          reactRoot <- createRoot container
          app <- myComponent
          renderRoot reactRoot (app {})

    myComponent :: Component {}
    myComponent =
      component "Test" \_ -> React.do
        pure $ R.script {children: [R.text "alert(1)"]}
    ```
4. Install deps as `spago install console effect exceptions maybe prelude react-basic react-basic-dom react-basic-hooks web-dom web-html`
5. Build it with `spago bundle-app`
6. Open `index.html` in a browser

## Expected

An alert should pop up

## Actual

No popups appear

**Comment by pete-murphy** [comment]
I think this is a limitation of React: I'm not able to get the equivalent
```js
import { createRoot } from "react-dom/client";

createRoot(document.getElementById("root")!).render(
  <script>console.log(1)</script>
);
```
to execute using React 18.3.1. Interestingly there's a workaround of changing the case of `<script>` to `<sCript>`. This works:
```js
createRoot(document.getElementById("root")!).render(
  <sCript>console.log(1)</sCript>
);
```

If you need to do this in PureScript, you could [try this](https://try.purescript.org/?github=JordanMartinezpurescript-cookbookmasterrecipesButtonsReactHookssrcMain.purs&code=LYewJgrgNgpgBAIQgF2SAdgZwEowIYDGyAEiCANaYB0AsngJbpwDuAFjAE4wBQ39wABxAdkcAApcoEMDz6DhogCJ5keWngCeAI3gAKOtpi6qVAJSm5QkXACiAMzswicXfcdEL-K6LdPkVGwAPAhgBZHoMF2RWDhBmT3lrXEJ-BDxMegIqRQB5Gjh0uGxLBSL8Iio0jKzcmioAYSh6GHRRXQIuFRhsMmQAGjgudBkOHpBkBO8ylMr0zKpSCkwXepB5dBb%2BuAI1oQ3WydLkiqr5xcoC5ePkEqTy1LmCFxhYYE3D6wB1GC1svKoAHIYGyvTZiPBDZBAmQuADmMGQIJgb1aCA0AEkwB9RN9fsQACo0AAyLmYjDAcWxcFxC0JRNpxMUIAIEBRbTQQPQSLZ4Mh0JgVJpBOJVE%2B5LiLgpLLZFluPgcfioAFUsHhHC4IKrHGJOHZhMBfB45XAVZg1TAGiBOCENVqYKtrQLeMAGEwAFxu2wK5wq%2Bg3F2MOAAXjgFO4cFDzLgAB4ALSR6WbYPR6MscXMcODXox%2BPwxGg1EYsBwABEsXGJbgABI4BzgQXkLzNvyE5mCOl4OXRCA7JmI0DooxYXBYwA%2BWsxCUl1bQYvocZwOzkrPjKglvtwABSEEwoh2rVdnBH47DEbPg3uY1Ece2nWQ3Wz%2B9UjE4G4jeAEAhzcGA5AAgp%2Bb4XsMnBXheKRgboH5fgA3gAvrKmD1Bw9BhMGcAvMiSa6JqZqOA6HA2jhdo6hweocAa3ptNgVC4eayH4PetSrOsSYlkhKFhCW5iyr%2BAFfh6cAsXsSbwdwfGfuhp7bLsGBsfiMC7pWAA6AD6x7TBU0kRgIEBcNWQE0WA9AAG6qUBEYANpwBxqGiDBBCsPQUBgEMnqWTR96BKIJb7pgICwFQUAgLCugAOTsFAwWLrEwA2chdlhaYJYALpwRZcApdwQA)
```purs
sCript = element (unsafeCoerce (unsafePerformEffect (R.unsafeCreateDOMComponent "sCript")))

mkApp :: Component {}
mkApp = do
  component "Test" \_ -> React.do
    pure $
      R.div_
        [ sCript {children: [R.text "console.log('hello from sCript')"]}
        ]
```

See also:
- https://github.com/facebook/react/blob/fe04dbcbc4185d7c9d7afebbe18589d2b681a88c/packages/react-dom-bindings/src/client/ReactFiberConfigDOM.js#L437-L451
- https://github.com/facebook/react/issues/19865

**Comment by Hi-Angel** [comment]
Wow, cool, thank you for the detailed explanation! And your workaround does work!

So… I suppose closing as the upstream React problem?

**Comment by pete-murphy** [comment]
> So… I suppose closing as the upstream React problem?

Yeah I think that makes sense 👍
